### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by johnktims** [querydsl/querydsl.com#5]
An icon would keep it from getting lost in all my tabs. :)

**Comment by Shredder121** [comment]
Seeing there [are](https://github.com/querydsl/querydsl.com/blob/master/releases.html#L9) already [entries](https://github.com/querydsl/querydsl.com/blob/master/index.html#L9) for the favicon, only the file should be added and it should work.
@timowest do you have a good copy of the original logo?

**Comment by timowest** [comment]
I will try to find one.

**Comment by johnktims** [comment]
I was just looking at the site and realized I can't find the logo anywhere. The only one I can find is on the twitter account.

**Comment by Shredder121** [comment]
Yes, me neither.
I found the twitter profile picture (not the original), github organization picture (also not original).
Yes, they could be used as baseline, but if @timowest has a (close to original) copy of the logo, then it's much easier.

**Comment by Shredder121** [comment]
[I uploaded the favicon, feel free to comment](https://github.com/querydsl/querydsl.com/compare/favicon)

**Comment by timowest** [comment]
For me it's displayed ok in Firefox, but not in Chrome. I am using Ubuntu 14.04.

**Comment by Shredder121** [comment]
Not in chrome? I am using a browser based on chromium.. but I'll have a look.

Also I have to re-export them, there was a mysterious layer added.

**Comment by Shredder121** [comment]
Or should I just export it without background? that is much easier.

**Comment by Shredder121** [comment]
Maybe a good question to ask: does it do anything out of the ordinary? does it display anything at all?

**Comment by timowest** [comment]
Sorry, I was too vague, in Chrome it shows only a white box.

**Comment by Shredder121** [comment]
How big was that box? if it was only a few pixels, could you try again now?

The second 'layer' was only a small white box, which was included in the ico. I removed it now.

**Comment by timowest** [comment]
Now it works for both Chrome and Firefox.

**Comment by Shredder121** [comment]
I now positioned it to use up more space (so it looks bigger)

It should now feel less out of place next to the other tabs.

Do you think the same?
(yes, I will squash the commits, when we find the right icon)

**Comment by timowest** [comment]
Yes, it looks good.

**Comment by johnktims** [comment]
Looks good to me in Chrome and Firefox. I don't have access to Internet Explorer.

**Comment by Shredder121** [comment]
I do have access to Internet Explorer, but can not check the way Internet Explorer behaves to see if it would work online(there is no favicon shown, so I can't say 'open in new tab', but it could well be because my local filesystem is not a good web server to Internet Explorer).
So I'll check when there is a real web page with the favicon.

**Comment by Shredder121** [comment]
In Internet Explorer I did a few runs for good measure, with clearing the cache in between(removing the favicon) and it works as well.

![ie favicon](https://cloud.githubusercontent.com/assets/4105066/6686929/4256a518-cca6-11e4-83cf-18752721d925.PNG)

**Comment by johnktims** [comment]
Cool. Thanks for following up on that.

**Comment by Shredder121** [comment]
Yes, I noticed a Querydsl favicon in between my tabs, while I thought I closed all my testing tabs...
Which I did; this was the real thing!
So it only felt natural to post the screenshot of IE.
